// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxdxmxzszgzgmohvemoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14ZHhteHpzemd6Z21vaHZlbW96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4OTQ5OTYsImV4cCI6MjA2MDQ3MDk5Nn0.Bb7QX9kuHm_vFSwmGG7MkvNVwsZTSFPUtcS0bKlD-oQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);